Seowonn: CS 운영체제 - 메모리 구조
KB-IT-s-Your-Life-Study/KB_CS_study pull request #1
Opened 2024-06-19 05:52 UTC by seowonn

06.20 CS 운영체제 - 메모리 구조 자료입니다.

2024-06-19 09:18 UTC, SangminHann requested changes
LGTM!

2024-06-19 09:18 UTC, SangminHann commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +        - JVM이 플랫폼과 관련된 작업들을 대신 해줌. 단 JVM은 플랫폼에 맞는 것으로 설치해야 한다.
JVM과 크로스 컴파일러의 차이에 대해서 궁금합니다.

2024-06-19 09:18 UTC, SangminHann commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +3. Class Loader를 통해 byte 코드를 JVM으로 로딩하게 된다.
로딩을 한다는 것이 어떤 것인지 궁금합니다.

2024-06-20 00:43 UTC, sooojChoi reviewed
수고하셨습니다!!!

2024-06-20 00:43 UTC, sooojChoi commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +4. 로딩된 바이트 코드(.class)는 Execution Engine을 통해 해석된다.
바이트 코드가 Execution Engine에 의해 해석된다는 것이 
Execution Engine가 인터프리터와 JIT 컴파일러 역할을 모두 수행하는 것인지 궁금합니다!

2024-06-20 00:43 UTC, sooojChoi commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +    - 어떤 명령을 실행해야 할지에 대한 기록(현재 수행중인 부분의 주소를 가짐)
결국 자바의 경우에 스레드 별로 독립적으로 할당되는 부분은 Stack과 PC register라고 보면 될까요? 그리고 PC register가 어떤 명령을 실행해야 할지에 대한 정보를 저장하고 있다는 말이, method영역의 코드 메모리 주소를 저장하고 있는 것인지 궁금합니다!

2024-06-20 01:39 UTC, seowonn commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +4. 로딩된 바이트 코드(.class)는 Execution Engine을 통해 해석된다.
넵 Execution Engine을 통해 인터프리터와 JIT 컴파일러 역할을 모두 수행합니다!
자바는 초기에는 인터프리터로 실행하고 이후 중복 코드를 재변환하는 불필요한 단계의 단점을 보완하기 위해  JIT 컴파일러를 같이 쓴다고 이해했습니다!

2024-06-20 02:00 UTC, gogoyubae commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +- 변수 선언은 초기화 과정과 상관 없이 선언이 된다. 이때 초기화된 전역 변수는 data 영역에, 초기화되지 않은 전역 변수는 BSS(block started by Symbol) 영역에 변수를 위치 시킨다.
BSS영역은 코드, 데이터, 힙, 스택 영역 중 어디에 속하나요? 아예 다른 영역이라면 어디인지 궁금합니다.

2024-06-20 04:05 UTC, seowonn commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +    - 어떤 명령을 실행해야 할지에 대한 기록(현재 수행중인 부분의 주소를 가짐)
넵! 쓰레드에 대해서는 제가 자세히는 모르겠으나 쓰레드 각각에는 Stack, PC Register, Native Method Stack을 보유하고 Heap과 Method Area는 모든 쓰레드가 같이 공유해서 쓰는 자원이라고 합니다! PC register는 method 영역의 코드 메모리 주소로 한정짓기 보단 JVM 에서 사용된 명령의 주소 값을 저장합니다

2024-06-20 04:07 UTC, seowonn commented on 메모리구조및자바메모리_손서원/[운영체제] 메모리 구조.md
> +- 변수 선언은 초기화 과정과 상관 없이 선언이 된다. 이때 초기화된 전역 변수는 data 영역에, 초기화되지 않은 전역 변수는 BSS(block started by Symbol) 영역에 변수를 위치 시킨다.
세부적으로 나누면 초기화된 전역 변수를 담는 곳과 초기화 되지 않은 전역 변수를 담은 것으로 data와 bss로 나눌 수 있는데 대개 넓게보면 데이터 영역으로 볼 수 있습니다!

2024-07-15 10:18 UTC, merged